### ISSUE TITLE
Review story SF-161: github code review: Incorporate milestones

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#10]
Story being reviewed: [SF-161](https://jira.salsitasoft.com/browse/SF-161)

SF-Issue-Tracker: JIRA
SF-Story-Key: SF-161

The associated commits are following:
- [x] 5aeb084: github/codereview: Implement review milestones
- [x] e4f36fd: github/codereview: Add review issues to milestones
- [x] 2ab1e51: github/codereview: Shorten milestone title
- [x] f7f5c9b: commands: Get rid of rollback code duplication

**Comment by tchap** [comment]
The following commits were added to this issue:
* ca1a7b6: github/codereview: Shorten milestone title

**Comment by tchap** [comment]
The following commits were added to this issue:
* 2ab1e51: github/codereview: Shorten milestone title

**Comment by tchap** [comment]
The following commits were added to this issue:
* b3c2685: commands: Get rid of rollback code duplication

**Comment by tchap** [comment]
The following commits were added to this issue:
* f7f5c9b: commands: Get rid of rollback code duplication
