### ISSUE TITLE
Review story #136: release deploy, not release stage should close the review milestone

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#137]
Story being reviewed: [#136](https://github.com/salsaflow/salsaflow/issues/136)

SF-Issue-Tracker: GitHub Issues
SF-Story-Key: salsaflow/salsaflow#136

The commits to be reviewed are following:
- [x] 60dd967: Finalise code review release during release deploy
- [x] f588256: modules/common: Fix a comment
- [x] da28ec3: code_review/github: Return ErrNotClosable

The following review blockers were opened by the reviewer:
- [x] [blocker 1](https://github.com/salsaflow/salsaflow/commit/60dd9677089bad17fe82d63294af1d1b78303d6c#commitcomment-14818942) (commit 60dd9677089bad17fe82d63294af1d1b78303d6c): replace `EnsureReleasable` with `EnsureClosable`

----------

The content above was generated by SalsaFlow.
You can insert custom description here, but not above the separator.

**Comment by tchap** [comment]
The following commits were added to this issue:
* f588256: modules/common: Fix a comment

**Comment by tchap** [comment]
The following commits were added to this issue:
* da28ec3: code_review/github: Return ErrNotClosable
