### ISSUE TITLE
Review story SF-197: Pivotal Tracker module is not assigning labels to stories on release start

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#45]
Story being reviewed: [SF-197](https://jira.salsitasoft.com/browse/SF-197)

SF-Issue-Tracker: JIRA
SF-Story-Key: SF-197

The commits to be reviewed are following:
- [x] dad9cda: releases: Fix ListNewTrunkCommits
- [x] de3c8bb: log: Print WARN and FAIL colored
- [x] 94fd3c3: jira+pivotaltracker: Only assign unassigned stories

----------

The content above was generated by SalsaFlow.
You can insert custom description here, but not above the separator.
