### ISSUE TITLE
Review story SF-200: Pivotal Tracker: Switch to the previous workflow

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#49]
Story being reviewed: [SF-200](https://jira.salsitasoft.com/browse/SF-200)

SF-Issue-Tracker: JIRA
SF-Story-Key: SF-200

The commits to be reviewed are following:
- [x] d1ac543: pivotaltracker: Revert to the origin workflow
- [x] 148f52e: repo bootstrap: Align the config template
- [x] 3f94185: pivotaltracker: Improve a code comment
- [x] da97f0a: common: Rename IssueTracker.StoriesInDevelopment

The following review blockers were opened by the reviewer:
- [x] [blocker 1](https://github.com/salsaflow/salsaflow/commit/d1ac543a27df31781c3d5624d031b6d4c5d0d6c2#commitcomment-12873595) (commit d1ac543a27df31781c3d5624d031b6d4c5d0d6c2): Maybe change StoriesInDevelopment to ListReviewableStories
- [x] [blocker 2](https://github.com/salsaflow/salsaflow/commit/d1ac543a27df31781c3d5624d031b6d4c5d0d6c2#commitcomment-12873874) (commit d1ac543a27df31781c3d5624d031b6d4c5d0d6c2): Remove unnecessary comment.

----------

The content above was generated by SalsaFlow.
You can insert custom description here, but not above the separator.

**Comment by tchap** [comment]
@mbernat This is actually still being discussed, so I am leaving the change in the story branch for now so that it doesn't get deployed automatically during the next release.

**Comment by tchap** [comment]
@mbernat Hmm, perhaps you don't need to review this for now.

**Comment by tchap** [comment]
@mbernat Please review this now, it is going to be a part of `0.14.0`, cheers.

**Comment by tchap** [comment]
The following commits were added to this issue:
* 3f94185: pivotaltracker: Improve a code comment

**Comment by tchap** [comment]
The following commits were added to this issue:
* da97f0a: common: Rename IssueTracker.StoriesInDevelopment
