### ISSUE TITLE
Review story SF-226: Implement an issue tracking module for GitHub

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#70]
Story being reviewed: [SF-226](https://jira.salsitasoft.com/browse/SF-226)

SF-Issue-Tracker: JIRA
SF-Story-Key: SF-226

The commits to be reviewed are following:
- [x] 0503bf2: code_review/github: Pull milestones into a package
- [x] deaf8e3: issue_tracking/github: Implement common.IssueTracker
- [x] 279bd76: issue_tracking/github: Implement common.NextRelease
- [x] 71c0505: issue_tracking/github: Implement common.RunningRelease
- [x] f14d0ee: issue_tracking/github: Fix missing semaphore
- [x] 96d9fb2: issue_tracking/github: Move code around
- [x] 7339c54: issue_tracking/github: Use updateIssues more
- [x] e96e2a0: prompt: Extend Dialog to handle structs recursively
- [x] fa9e38b: issue_tracking/github: Use prompt.Dialog
- [x] 36d7ea8: issue_tracking/github: Refactor setStateLabel

The following review blockers were opened by the reviewer:
- [x] [blocker 1](https://github.com/salsaflow/salsaflow/commit/deaf8e3461c2a0e49292a4a90dca75e320d5440f#commitcomment-13594533) (commit deaf8e3461c2a0e49292a4a90dca75e320d5440f): Move this to the bottom of the file, that would make more sense.
- [x] [blocker 2](https://github.com/salsaflow/salsaflow/commit/deaf8e3461c2a0e49292a4a90dca75e320d5440f#commitcomment-13594790) (commit deaf8e3461c2a0e49292a4a90dca75e320d5440f): Might be better to extend `prompt.Dialog` to be able to handle nested structs.
- [x] [blocker 3](https://github.com/salsaflow/salsaflow/commit/deaf8e3461c2a0e49292a4a90dca75e320d5440f#commitcomment-13594930) (commit deaf8e3461c2a0e49292a4a90dca75e320d5440f): Set to `salsaflow.modules.issuetracking.github`
- [x] [blocker 4](https://github.com/salsaflow/salsaflow/commit/deaf8e3461c2a0e49292a4a90dca75e320d5440f#commitcomment-13594973) (commit deaf8e3461c2a0e49292a4a90dca75e320d5440f): Use `tracker.updateIssues` instead.
- [x] [blocker 5](https://github.com/salsaflow/salsaflow/commit/deaf8e3461c2a0e49292a4a90dca75e320d5440f#commitcomment-13595000) (commit deaf8e3461c2a0e49292a4a90dca75e320d5440f): Might make sense to use `tracker.updateIssues` as well...

----------

The content above was generated by SalsaFlow.
You can insert custom description here, but not above the separator.

**Comment by tchap** [comment]
The following commits were added to this issue:
* f14d0ee: issue_tracking/github: Fix missing semaphore

**Comment by tchap** [comment]
The following commits were added to this issue:
* 96d9fb2: issue_tracking/github: Move code around

**Comment by tchap** [comment]
The following commits were added to this issue:
* 7339c54: issue_tracking/github: Use updateIssues more

**Comment by tchap** [comment]
The following commits were added to this issue:
* e96e2a0: prompt: Extend Dialog to handle structs recursively
* fa9e38b: issue_tracking/github: Use prompt.Dialog

**Comment by tchap** [comment]
The following commits were added to this issue:
* 36d7ea8: issue_tracking/github: Refactor setStateLabel
