### ISSUE TITLE
SF should not be pushing story branches by default

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#84]
`story start` should not be pushing the newly created story branch by default and `review post` should not be pushing the story branch unless it exists in the remote repository. The GitHub code review module should be generating full URL links to the commits, not count on GitHub to find the commit hashes and link them automatically. This makes it possible to push the commits after the associated review issue is created, e.g. after merging them into develop.

The issue is, though, that some modules may require the branch to exist remotely. So it should be possible that somehow specify that in case particular module is being used, the story has to be pushed. These modules should probably simply push the branch themselves for now.

## Tasks ##

- [x] `story start`: Replace `-no_push` with `-push`, making `story start` not push the newly created story branch by default.
- [x] `review post`: Change the flags to include `-no_merge`. The behaviour should change so that when `-parent` is specified, the current branch is merged into the parent branch unless `-no_merge` is specified. This makes it obvious whether we need to push the story branch or not. In case `-no_merge` is specified, we need to push the story branch, otherwise we can merge into the parent branch and push that branch instead. The tip mode of `review post` always needs to push the branch, obviously. When merging, the user should be prompted whether they want to use `--no-ff`.

**Comment by tchap** [comment]
What needs to be done:

- `story start`: Replace `-no_push` with `-push=BOOLEAN`, although there should be also some interactive prompt in case the flag is not specified.
- `review post`: Only push the branch being posted for review in case the branch is tracking a remote branch from the project repository.
- `github/issues` package: Change the review issue parser/generator to use full URLs to the commits instead of depending on GitHub to recognise the hashes.
- salsaflow/salsaflow-daemon: Update dependencies to include the updated review issue parser.

**Comment by tchap** [comment]
I am leaving this for the next release, reverted the commits that were already on develop.

**Comment by tchap** [comment]
Tested

- [ ] review post -parent when branch not pushed -> merge into parent and push parent
- [ ] review post -parent when branch pushed -> push branch, merge into parent and push parent
- [ ] review post -parent -no_merge when branch not pushed -> push branch
- [ ] review post -parent -no_merge when branch pushed -> force push branch
- [ ] review post -parent -merge_no_ff -> merge using --no-ff

**Comment by tchap** [comment]
Tested.
